server:
  port: 9131
spring:
  application:
    name: management
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1  #采集率 默认0.1 即 10%
eureka:
  client:
    fetch-registry: true #是否从eureka中获取信息
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
